name: Publish package

on:
  push:
    paths:
      - build.sh
      - .github/workflows/publish.yml

jobs:
  build-nodejs-deb:
    runs-on: ubuntu-latest
    container:
      image: debian:sid

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        apt update
        apt install dpkg ffmpeg libsdl2-2.0-0 adb wget \
                 gcc git pkg-config meson ninja-build libsdl2-dev \
                 libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev \
                 libswresample-dev libusb-1.0-0 libusb-1.0-0-dev -y

    - name: Build Deb File
      run: |
        bash build.sh

    - name: Automatic Release
      uses: marvinpinto/action-automatic-releases@latest
      with: 
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Latest Build"
        files: |
          *.deb
